services:
  - type: web
    name: optiflow-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    plan: free

  - type: web
    name: optiflow-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_SERVER_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
